# Generated by Django 3.2.6 on 2021-08-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Male', 'Male'), ('Other', 'Other')], default='', max_length=255),
        ),
    ]
